In [58]:
import pandas as pd
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [59]:
# reading the data and looking at the first five rows of the data
data=pd.read_csv("Collabrative.csv")
data.head()

ItemLookupcode                       Product_Line  CustomerID   FirstName  \
0              51  True Citrus - Crystallized Citrus       82140     Elspeth   
1              51  True Citrus - Crystallized Citrus       84468       Paul    
2              51  True Citrus - Crystallized Citrus       90114       Leah    
3              51  True Citrus - Crystallized Citrus       91751  Stephanie    
4              51  True Citrus - Crystallized Citrus       91790     Andrea    

   Quantity  sales  
0        96    472  
1       144    712  
2        72    360  
3        24    120  
4        48    240

In [60]:
data=data[['CustomerID','ItemLookupcode','Quantity']]

In [61]:
data

CustomerID  ItemLookupcode  Quantity
0           82140              51        96
1           84468              51       144
2           90114              51        72
3           91751              51        24
4           91790              51        48
...           ...             ...       ...
18714  1073845375               8         8
18715  1073835810               9         4
18716  1073838933               9         4
18717  1073838937               9         4
18718  1073849196               9         8

[18719 rows x 3 columns]

In [62]:
#table =pd.pivot_table(data, values ='units', index=['ItemLookupcode','Product_Line'],columns=['CustomerID'], aggfunc=np.sum)
n_customer = data.CustomerID.unique().shape[0]
n_items = data.ItemLookupcode.unique().shape[0]

In [160]:
data.CustomerID.unique()

array([     82140,      84468,      90114,      91751,      91790,
       1073745835, 1073747284, 1073747545, 1073747888, 1073748767,
       1073748827, 1073749833, 1073760295, 1073761820, 1073762092,
       1073762148, 1073764571, 1073767519, 1073767575, 1073768454,
       1073768630, 1073768645, 1073768721, 1073773723, 1073775053,
       1073776133, 1073779502, 1073781151, 1073781517, 1073781747,
       1073784378, 1073792891, 1073797413, 1073800300, 1073802019,
       1073815953, 1073832045, 1073833130, 1073837855, 1073837990,
       1073838918, 1073839478, 1073841539, 1073843416, 1073845029,
            88052, 1073746558, 1073759653, 1073764509, 1073801876,
       1073829744,      11594,      77744,      80851,      81743,
            81886,      85600,      87550,      87862,      90008,
            90754,      92148, 1073746018, 1073750005, 1073765927,
       1073768553, 1073769875, 1073770549, 1073775057, 1073778403,
       1073778521, 1073778650, 1073779922, 1073788529, 1073789

In [63]:
#g = data.groupby("units")
n_customer

619

In [64]:
n_items

452

In [167]:
data_pivot=pd.pivot_table(data,values='Quantity',index=['CustomerID'],columns=['ItemLookupcode'],aggfunc=np.sum)
data_customer=pd.pivot_table(data,values='Quantity',index=['CustomerID'],columns=['ItemLookupcode'],aggfunc=np.sum)

In [168]:
#data_pivot['CustomerID']
data_customer.reset_index(level=0, inplace=True) 
data_customer=data_customer['CustomerID']

In [170]:
data_pivot.head()

ItemLookupcode  1     2     3     4     5     6     7     8     9     51    \
CustomerID                                                                   
11594            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
14360            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
16359            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
18844            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
27497            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

ItemLookupcode  ...  9771  9772  9773  9774  9775  9845  9846   9847  9848  \
CustomerID      ...                                                          
11594           ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   
14360           ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   
16359           ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   
18844           ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   
27497           ...   NaN   NaN   NaN   NaN   NaN  96.0   NaN  288.0   NaN   

ItemLookupcode  9849  
CustomerID            
11594            NaN  
14360            NaN  
16359            NaN  
18844            NaN  
27497            NaN  

[5 rows x 452 columns]

In [171]:
data_pivot=data_pivot.fillna(0)

In [172]:
data_pivot.head()

ItemLookupcode  1     2     3     4     5     6     7     8     9     51    \
CustomerID                                                                   
11594            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
14360            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
16359            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
18844            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
27497            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

ItemLookupcode  ...  9771  9772  9773  9774  9775  9845  9846   9847  9848  \
CustomerID      ...                                                          
11594           ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
14360           ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
16359           ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
18844           ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
27497           ...   0.0   0.0   0.0   0.0   0.0  96.0   0.0  288.0   0.0   

ItemLookupcode  9849  
CustomerID            
11594            0.0  
14360            0.0  
16359            0.0  
18844            0.0  
27497            0.0  

[5 rows x 452 columns]

In [173]:

data_pivot.reset_index(drop=True, inplace=True)


In [174]:
data_pivot.head()

ItemLookupcode  1     2     3     4     5     6     7     8     9     51    \
0                0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
1                0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2                0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3                0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4                0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

ItemLookupcode  ...  9771  9772  9773  9774  9775  9845  9846   9847  9848  \
0               ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
1               ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
2               ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
3               ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   
4               ...   0.0   0.0   0.0   0.0   0.0  96.0   0.0  288.0   0.0   

ItemLookupcode  9849  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0  

[5 rows x 452 columns]

In [178]:
#from sklearn.metrics import jaccard_similarity_score
        #from itertools import islice

def take(n, iterable):
    "Return first n items of the iterable as a list"
    return list(islice(iterable, n))

cust_list=[]
for each_row in range(len(data_pivot)-1):
    similarity_dict={}
    for each in range(len(data_pivot)-1):
        a=jaccard_similarity_score(data_pivot.iloc[each_row], data_pivot.iloc[each])
        similarity_dict[data_customer.iloc[each]]=a
        similarity_dict={k: v for k, v in sorted(similarity_dict.items(), key=lambda item: item[1],reverse=True)}
        top_similar_customers=take(11, similarity_dict.items())
    cust_list.append(top_similar_customers)
    
    

In [183]:
data_cust=pd.DataFrame.from_dict(cust_list)

In [184]:
data_cust

0                                 1  \
0         (11594, 1.0)       (90922, 0.9491150442477876)   
1         (14360, 1.0)       (18844, 0.8539823008849557)   
2         (16359, 1.0)  (1073748573, 0.9690265486725663)   
3         (18844, 1.0)                 (1073849549, 1.0)   
4         (27497, 1.0)       (81410, 0.8628318584070797)   
..                 ...                               ...   
613  (1073851847, 1.0)  (1073827593, 0.9867256637168141)   
614  (1073852190, 1.0)   (1073851532, 0.995575221238938)   
615  (1073852542, 1.0)  (1073837986, 0.9800884955752213)   
616  (1073852602, 1.0)  (1073810389, 0.9933628318584071)   
617  (1073852611, 1.0)       (90459, 0.9867256637168141)   

                                    2                                 3  \
0    (1073748573, 0.9491150442477876)  (1073772436, 0.9491150442477876)   
1         (81410, 0.8539823008849557)       (86722, 0.8539823008849557)   
2    (1073765804, 0.9690265486725663)  (1073791097, 0.9690265486725663)   
3          (90922, 0.995575221238938)   (1073748573, 0.995575221238938)   
4         (84986, 0.8628318584070797)       (86722, 0.8628318584070797)   
..                                ...                               ...   
613  (1073801119, 0.9845132743362832)  (1073828623, 0.9845132743362832)   
614       (18844, 0.9911504424778761)       (90922, 0.9911504424778761)   
615  (1073839296, 0.9800884955752213)  (1073804230, 0.9778761061946902)   
616       (18844, 0.9911504424778761)       (90922, 0.9911504424778761)   
617  (1073752234, 0.9867256637168141)  (1073839476, 0.9867256637168141)   

                                    4                                 5  \
0    (1073777955, 0.9491150442477876)  (1073814007, 0.9491150442477876)   
1         (90922, 0.8539823008849557)  (1073748573, 0.8539823008849557)   
2    (1073838240, 0.9690265486725663)  (1073838464, 0.9690265486725663)   
3     (1073752234, 0.995575221238938)   (1073759236, 0.995575221238938)   
4         (88130, 0.8628318584070797)       (90922, 0.8628318584070797)   
..                                ...                               ...   
613  (1073831579, 0.9845132743362832)  (1073837986, 0.9845132743362832)   
614  (1073748573, 0.9911504424778761)  (1073752234, 0.9911504424778761)   
615  (1073814007, 0.9778761061946902)  (1073838240, 0.9778761061946902)   
616  (1073748573, 0.9911504424778761)  (1073752234, 0.9911504424778761)   
617  (1073839675, 0.9867256637168141)  (1073850513, 0.9867256637168141)   

                                    6                                 7  \
0    (1073833599, 0.9491150442477876)  (1073838240, 0.9491150442477876)   
1    (1073759236, 0.8539823008849557)  (1073767060, 0.8539823008849557)   
2    (1073846187, 0.9690265486725663)  (1073850065, 0.9690265486725663)   
3     (1073761354, 0.995575221238938)   (1073780948, 0.995575221238938)   
4    (1073748573, 0.8628318584070797)  (1073759236, 0.8628318584070797)   
..                                ...                               ...   
613  (1073838240, 0.9845132743362832)  (1073838464, 0.9845132743362832)   
614  (1073759236, 0.9911504424778761)  (1073761354, 0.9911504424778761)   
615  (1073838464, 0.9778761061946902)  (1073846187, 0.9778761061946902)   
616  (1073759236, 0.9911504424778761)  (1073761354, 0.9911504424778761)   
617  (1073780948, 0.9845132743362832)  (1073822957, 0.9845132743362832)   

                                    8                                 9  \
0    (1073838464, 0.9491150442477876)  (1073845312, 0.9491150442477876)   
1    (1073768747, 0.8539823008849557)  (1073772436, 0.8539823008849557)   
2    (1073850624, 0.9690265486725663)       (18844, 0.9668141592920354)   
3     (1073791097, 0.995575221238938)   (1073792515, 0.995575221238938)   
4    (1073772436, 0.8628318584070797)  (1073788164, 0.8628318584070797)   
..                                ...                               ...   
613  (1073838718, 0.9845132743362832)  (1073839715, 0.9845132743362832) 

In [188]:
data_cust.reset_index(drop=True, inplace=True)

In [189]:
data_cust.head()

0                                 1  \
0  (11594, 1.0)       (90922, 0.9491150442477876)   
1  (14360, 1.0)       (18844, 0.8539823008849557)   
2  (16359, 1.0)  (1073748573, 0.9690265486725663)   
3  (18844, 1.0)                 (1073849549, 1.0)   
4  (27497, 1.0)       (81410, 0.8628318584070797)   

                                  2                                 3  \
0  (1073748573, 0.9491150442477876)  (1073772436, 0.9491150442477876)   
1       (81410, 0.8539823008849557)       (86722, 0.8539823008849557)   
2  (1073765804, 0.9690265486725663)  (1073791097, 0.9690265486725663)   
3        (90922, 0.995575221238938)   (1073748573, 0.995575221238938)   
4       (84986, 0.8628318584070797)       (86722, 0.8628318584070797)   

                                  4                                 5  \
0  (1073777955, 0.9491150442477876)  (1073814007, 0.9491150442477876)   
1       (90922, 0.8539823008849557)  (1073748573, 0.8539823008849557)   
2  (1073838240, 0.9690265486725663)  (1073838464, 0.9690265486725663)   
3   (1073752234, 0.995575221238938)   (1073759236, 0.995575221238938)   
4       (88130, 0.8628318584070797)       (90922, 0.8628318584070797)   

                                  6                                 7  \
0  (1073833599, 0.9491150442477876)  (1073838240, 0.9491150442477876)   
1  (1073759236, 0.8539823008849557)  (1073767060, 0.8539823008849557)   
2  (1073846187, 0.9690265486725663)  (1073850065, 0.9690265486725663)   
3   (1073761354, 0.995575221238938)   (1073780948, 0.995575221238938)   
4  (1073748573, 0.8628318584070797)  (1073759236, 0.8628318584070797)   

                                  8                                 9  \
0  (1073838464, 0.9491150442477876)  (1073845312, 0.9491150442477876)   
1  (1073768747, 0.8539823008849557)  (1073772436, 0.8539823008849557)   
2  (1073850624, 0.9690265486725663)       (18844, 0.9668141592920354)   
3   (1073791097, 0.995575221238938)   (1073792515, 0.995575221238938)   
4  (1073772436, 0.8628318584070797)  (1073788164, 0.8628318584070797)   

                                 10  
0  (1073846187, 0.9491150442477876)  
1  (1073775202, 0.8539823008849557)  
2       (90922, 0.9668141592920354)  
3   (1073801119, 0.995575221238938)  
4  (1073791097, 0.8628318584070797)

In [185]:
pd.merge(data_cust,data,on='CustomerID')

KeyError: 'CustomerID'

In [181]:
cust_list

[[(11594, 1.0),
  (90922, 0.9491150442477876),
  (1073748573, 0.9491150442477876),
  (1073772436, 0.9491150442477876),
  (1073777955, 0.9491150442477876),
  (1073814007, 0.9491150442477876),
  (1073833599, 0.9491150442477876),
  (1073838240, 0.9491150442477876),
  (1073838464, 0.9491150442477876),
  (1073845312, 0.9491150442477876),
  (1073846187, 0.9491150442477876)],
 [(14360, 1.0),
  (18844, 0.8539823008849557),
  (81410, 0.8539823008849557),
  (86722, 0.8539823008849557),
  (90922, 0.8539823008849557),
  (1073748573, 0.8539823008849557),
  (1073759236, 0.8539823008849557),
  (1073767060, 0.8539823008849557),
  (1073768747, 0.8539823008849557),
  (1073772436, 0.8539823008849557),
  (1073775202, 0.8539823008849557)],
 [(16359, 1.0),
  (1073748573, 0.9690265486725663),
  (1073765804, 0.9690265486725663),
  (1073791097, 0.9690265486725663),
  (1073838240, 0.9690265486725663),
  (1073838464, 0.9690265486725663),
  (1073846187, 0.9690265486725663),
  (1073850065, 0.9690265486725663),
  (

In [158]:
similarity_dict={k: v for k, v in sorted(similarity_dict.items(), key=lambda item: item[1],reverse=True)}

In [155]:
from itertools import islice

def take(n, iterable):
    "Return first n items of the iterable as a list"
    return list(islice(iterable, n))
take(11, similarity_dict.items())

[(0, 1.0),
 (49, 0.9491150442477876),
 (84, 0.9491150442477876),
 (163, 0.9491150442477876),
 (202, 0.9491150442477876),
 (319, 0.9491150442477876),
 (399, 0.9491150442477876),
 (454, 0.9491150442477876),
 (459, 0.9491150442477876),
 (543, 0.9491150442477876),
 (555, 0.9491150442477876)]

In [106]:
from sklearn.metrics.pairwise import pairwise_distances
jac_sim = 1 - pairwise_distances(data_pivot, metric = "hamming")
# optionally convert it to a DataFrame
#jac_sim = pd.DataFrame(jac_sim, index=df.columns, columns=df.columns)

In [107]:
jac_sim

array([[1.        , 0.82743363, 0.92920354, ..., 0.94247788, 0.93584071,
        0.93141593],
       [0.82743363, 1.        , 0.84734513, ..., 0.84955752, 0.84070796,
        0.84070796],
       [0.92920354, 0.84734513, 1.        , ..., 0.96238938, 0.95575221,
        0.95353982],
       ...,
       [0.94247788, 0.84955752, 0.96238938, ..., 1.        , 0.97787611,
        0.97787611],
       [0.93584071, 0.84070796, 0.95575221, ..., 0.97787611, 1.        ,
        0.96460177],
       [0.93141593, 0.84070796, 0.95353982, ..., 0.97787611, 0.96460177,
        1.        ]])

In [112]:
jac_sim = pd.DataFrame(jac_sim, index=data.columns, columns=data.columns)
#index=['CustomerID'],columns=['ItemLookupcode']

ValueError: Shape of passed values is (619, 619), indices imply (3, 3)

In [73]:
user_item_matrix = np.zeros((n_customer, n_items))
for line in data.itertuples():
    user_item_matrix[line[1] - 1, line[2] - 1] = line[3]
#print(user_item_matrix)

IndexError: index 82139 is out of bounds for axis 0 with size 619

In [70]:
user_item_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
data.fillna(0)

CustomerID  ItemLookupcode  Quantity
0           82140              51        96
1           84468              51       144
2           90114              51        72
3           91751              51        24
4           91790              51        48
...           ...             ...       ...
18714  1073845375               8         8
18715  1073835810               9         4
18716  1073838933               9         4
18717  1073838937               9         4
18718  1073849196               9         8

[18719 rows x 3 columns]

In [49]:
data.itertuples()

In [50]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [51]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [52]:
def predict(data, similarity, type='user'):
    if type == 'user':
        mean_user_data = data.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        data_diff = (data - mean_user_data[:, np.newaxis])
        pred = mean_user_data[:, np.newaxis] + similarity.dot(data_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = data.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [53]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [54]:
user_prediction

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

ModuleNotFoundError: No module named 'turicreate'